language: node_js
node_js: 
- "0.10"
deploy: 
  api_key: 
    secure: X+7MOqJWICID/KYdUVHIYeUMduN5NDRiksO+S/P3RLM/vsKUkJrE5ZTMjsmghaXeC3L3t34PlR2FFTnh7vspZMfRdLggr5jPG4YdidfbGEwXvnaVPvkPadZp/ZD3wixlpSS2j6KHyYv49yM16G9SqWp0s72q81jrkKmKB1yDkp0=
  on: heroku
  app: foodninja
  provider: heroku